spring:
  application:
    name: tracker-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/tracker_db
      database: tracker_db

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
